fixtures:
  repositories:
    cron_core:
      repo: "https://github.com/puppetlabs/puppetlabs-cron_core"
      puppet_version: '>= 6.0.0'
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib"
  symlinks:
    certificate_checker: "#{source_dir}"
